### ISSUE TITLE
v2.0-dev ifCommand failed numerous debug tests

### ISSUE THREAD

**Issue by cassitly** [Nxium-Developments/NextLanguage#18]
The debug file has outputted many errors. ifCommand has failed most tests. In v2.0-dev

```output
Error evaluating condition: x > 10
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
x is not greater than 10
Error evaluating condition: x === 11
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
x is not equal to 11
Error evaluating condition: x < 9
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
x is bigger than 9
Error evaluating condition: percentage === 11%
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
percentage isn't equal to 11%
Error evaluating condition: boolean
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
boolean is false
Error evaluating condition: decimal === 0.1
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
decimal isn't equal to 0.1
Error evaluating condition: decimal > 0.1
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
decimal isn't greater than 0.1
Error evaluating condition: decimal < 0.1
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
decimal is bigger than 0.1
Error evaluating condition: boolean
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
boolean is false
```

**Comment by reveryx** [comment]
The ifStatementHandler.js is shit. How scuffed is this???

```javascript
// Local Imports for logging and Evaluations
const addOutput = require('./addOutput');
const safeEval = require('./safeEval');

module.exports = function IfStatementHandler() {
    /**
     * Parses and executes `if` statements.
     * @param {string} line - The NXL code line containing the if statement.
     * @param {Object} localVariables - The variables available in the current scope.
     */
    function parseIfStatement(line, lines) {
        // Match the 'if' condition and the associated blocks.
        const conditionMatch = line.match(/@if \[(.+?)\]:/);
        
        if (conditionMatch) {
            const [, condition] = conditionMatch;
            
            // Safely evaluate the condition in the current scope.
            const conditionValue = safeEval(condition);

            // Separates the if and else blocks.
            const ifBlock = lines.slice(lines.indexOf(line) + 1).join('\n').split('\n@else' || '\n@end')[0];
            const elseBlock = lines.slice(lines.indexOf(line) + 3).join('\n').split('\n@end')[0];
            
            // Determine which block to execute based on the condition.
            const blockToExecute = conditionValue ? ifBlock : elseBlock;
        

            // If the block to execute starts with ":output", handle the output.
            if (blockToExecute.startsWith(":output")) {
                // Separates the contents of @output
                const outputContent = blockToExecute.split(':output').slice(1).join('\n').split('\n:end')[0].trim();
                addOutput(outputContent); // Outputs the contents
            }
        } else {
            // Handle invalid syntax or other conditions
            addOutput('Invalid if statement syntax:' + line);
        }
    }

    return {
        parseIfStatement,
    };
};
```

**Comment by cassitly** [comment]
Condition 1
```
Error evaluating condition: x > 10
TypeError: getVariables is not a function
    at C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:11:35
    at String.replace (<anonymous>)
    at safeEval (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\safeEval.js:9:45)
    at Object.parseIfStatement (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\modules\functions\IfStatementHandler.js:19:36)
    at ifCommand (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\patches\v1.9\modules\if.js:4:19)
    at compiler (C:\Users\jedik\Documents\GitHub\Project Next\Products\NextLanguage\NextLanguage-Source\package\interpreter.js:111:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
x is not greater than 10
```
